apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-ingress
spec:
  ingressClassName: nginx   # ðŸ”¥ THIS LINE IS CRITICAL
  rules:
    - host: login.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: login-k8
                port:
                  number: 3000
